### ISSUE TITLE
Display freezing: Assertion Failed. Failed to process POST_EVENT with status 0x57

### ISSUE THREAD

**Issue by MeguminSama** [NVIDIA/open-gpu-kernel-modules#739]
Seemingly at random, one display will completely freeze until I reboot. The other displays continue to work just fine. If I restart the monitor, all of my remaining displays will freeze. All monitors are DisplayPort, connected to an RTX 3070 Ti.

Running on
```
Arch Linux
Wayland 1.23.1
KDE Plasma 6.2.3
Linux 6.11.7 (Zen Kernel)
``` 

dmesg output is just:

```
~ sudo dmesg
...
[  286.249080] NVRM: nvAssertFailedNoLog: Assertion failed: CliGetEventInfo(rpc_params->hClient, rpc_params->hEvent, &pEvent) @ kernel_gsp.c:462
[  286.249091] NVRM: _kgspProcessRpcEvent: Failed to process received event 0x1003 (POST_EVENT) from GPU0: status=0x57
```

With the following NVIDIA packages installed:

```
~ paru -Q | grep nvidia
lib32-nvidia-utils 565.57.01-1
libva-nvidia-driver 0.0.13-1
nvidia-open-dkms 565.57.01-1
nvidia-utils 565.57.01-1
opencl-nvidia 565.57.01-1
```

Relevant code:

https://github.com/NVIDIA/open-gpu-kernel-modules/blob/d5a0858f901d15bda4c3d6db19a271507722a860/src/nvidia/src/kernel/gpu/gsp/kernel_gsp.c#L462-L463

## Workarounds

For people coming here looking for workarounds to this issue:

Use CTRL+ALT+F3 (or any other relevant function key) to change TTY. Then, switch back to your previous TTY using CTRL+ALT+F1 (if you don't know your TTY, just go up through F1, F2, etc. until you're back in your desktop environment)

**Comment by foophoof** [comment]
I think I have this issue too.

Running Bazzite 41 (from Fedora Kinoite), Linux 6.11.8-305.bazzite.fc41.x86_64, AMD Ryzen 9 5900X, NVIDIA GeForce RTX 3080 Ti, KDE Plasma 6.2.3, Wayland 1.23.0.

```
$ rpm -qa | /bin/grep nvidia
nvidia-gpu-firmware-20241110-1.fc41.noarch
ublue-os-nvidia-addons-0.10-1.fc41.noarch
libnvidia-ml-565.57.01-4.fc41.x86_64
libnvidia-cfg-565.57.01-4.fc41.x86_64
nvidia-driver-cuda-libs-565.57.01-4.fc41.x86_64
nvidia-persistenced-565.57.01-1.fc41.x86_64
nvidia-driver-libs-565.57.01-4.fc41.x86_64
nvidia-container-toolkit-base-1.17.2-1.x86_64
libnvidia-container1-1.17.2-1.x86_64
libnvidia-container-tools-1.17.2-1.x86_64
nvidia-modprobe-565.57.01-1.fc41.x86_64
kmod-nvidia-565.57.01-1.fc41.x86_64
nvidia-kmod-common-565.57.01-2.fc41.noarch
nvidia-driver-565.57.01-4.fc41.x86_64
nvidia-libXNVCtrl-565.57.01-1.fc41.x86_64
libnvidia-ml-565.57.01-4.fc41.i686
nvidia-settings-565.57.01-1.fc41.x86_64
xorg-x11-nvidia-565.57.01-4.fc41.x86_64
nvidia-driver-cuda-565.57.01-4.fc41.x86_64
nvidia-container-toolkit-1.17.2-1.x86_64
libnvidia-fbc-565.57.01-4.fc41.x86_64
libva-nvidia-driver-0.0.13^20241108git259b7b7-1.fc41.x86_64
nvidia-driver-libs-565.57.01-4.fc41.i686
nvidia-driver-cuda-libs-565.57.01-4.fc41.i686

```

systemd journal:

```
Nov 19 21:23:18 bazzite kwin_wayland[2537]: kwin_wayland_drm: atomic commit failed: Invalid argument
Nov 19 21:23:20 bazzite kwin_wayland[2537]: kwin_wayland_drm: atomic commit failed: Invalid argument
Nov 19 21:26:38 bazzite kwin_wayland[2537]: kwin_wayland_drm: atomic commit failed: Invalid argument
Nov 19 21:28:15 bazzite kwin_wayland[2537]: kwin_wayland_drm: atomic commit failed: Invalid argument
Nov 19 21:29:09 bazzite kernel: NVRM: nvAssertFailedNoLog: Assertion failed: CliGetEventInfo(rpc_params->hClient, rpc_params->hEvent, &pEvent) @ kernel_gsp.c:462
Nov 19 21:29:09 bazzite kernel: NVRM: _kgspProcessRpcEvent: Failed to process received event 0x1003 (POST_EVENT) from GPU0: status=0x57
Nov 19 21:29:27 bazzite steam[3128]: ERROR: ld.so: object '/usr/lib/extest/libextest.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
Nov 19 21:29:27 bazzite steam[3128]: ERROR: ld.so: object '/usr/lib/extest/libextest.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
Nov 19 21:29:31 bazzite kwin_wayland[2537]: kwin_wayland_drm: Pageflip timed out! This is a kernel bug
Nov 19 21:29:36 bazzite kwin_wayland[2537]: kwin_wayland_drm: Pageflip timed out! This is a kernel bug
Nov 19 21:29:41 bazzite kwin_wayland[2537]: kwin_wayland_drm: Pageflip timed out! This is a kernel bug
Nov 19 21:29:46 bazzite kwin_wayland[2537]: kwin_wayland_drm: Pageflip timed out! This is a kernel bug
Nov 19 21:29:51 bazzite kwin_wayland[2537]: kwin_wayland_drm: Pageflip timed out! This is a kernel bug
Nov 19 21:29:56 bazzite kwin_wayland[2537]: kwin_wayland_drm: Pageflip timed out! This is a kernel bug
```

Not 100% sure exactly when in this log things froze, but probably around 21:29 around the assertion failure.

**Comment by mtijanic** [comment]
Hi! Thanks for the report! The assert itself looks like a race condition that shouldn't be fatal by itself, but it's probably indicative of the larger problem. Can you please run `nvidia-bug-report.sh` as soon as you hit this issue and attach the logs?

(also, please respect the bug template, it helps us with triage and makes it less likely your issues will get lost)

**Comment by Exotic0015** [comment]
The same issue has been reported on Nvidia forums:
https://forums.developer.nvidia.com/t/565-release-feedback-discussion/310777/115
https://forums.developer.nvidia.com/t/565-release-feedback-discussion/310777/118

**Comment by ptr1337** [comment]
Faced this issue also while playing Diablo 4:
```
[ 2244.525940] NVRM: nvAssertFailedNoLog: Assertion failed: CliGetEventInfo(rpc_params->hClient, rpc_params->hEvent, &pEvent) @ kernel_gsp.c:463
[ 2244.525948] NVRM: _kgspProcessRpcEvent: Failed to process received event 0x1003 (POST_EVENT) from GPU0: status=0x57
[ 2294.820903] r8169 0000:0b:00.0: invalid VPD tag 0xff (size 0) at offset 0; assume missing optional EEPROM
```

[nvidia-bug-report.log.gz](https://github.com/user-attachments/files/17827550/nvidia-bug-report.log.gz)

**Comment by MeguminSama** [comment]
@mtijanic apologies for not following the template - I opened the issue from the line of code where the error occurred, so didn't get shown the template flow.

I just had the issue occur again, so I've attached the log here.

[nvidia-bug-report.log.gz](https://github.com/user-attachments/files/17835290/nvidia-bug-report.log.gz)

**Comment by mtijanic** [comment]
Thanks! And the lack of template issue is entirely on github. I knew this happened if you go through the `new issue -> create account -> finish new issue` flow, but this one is new to me.

I'll get back to you tomorrow on the log analysis, the one above from ptr1337 unfortunately didn't yield too much useful info.

**Comment by foophoof** [comment]
For a workaround, I've found that if I switch to one of the console TTYs (Ctrl-Alt-1/2/3/4/5/6 usually depending on distro) and then back again things unfreeze.

**Comment by MeguminSama** [comment]
@mtijanic just wondering if you managed to spot anything? No worries if you haven't gotten around to it yet though :)

**Comment by mtijanic** [comment]
Hi! I only had a chance for a quick pass and didn't really see anything actionable. Over the next few days I'll try to do more detailed pass over the logs. Interestingly, I did come across these exact prints:
```
Nov 19 21:29:31 bazzite kwin_wayland[2537]: kwin_wayland_drm: Pageflip timed out! This is a kernel bug
Nov 19 21:29:36 bazzite kwin_wayland[2537]: kwin_wayland_drm: Pageflip timed out! This is a kernel bug
Nov 19 21:29:41 bazzite kwin_wayland[2537]: kwin_wayland_drm: Pageflip timed out! This is a kernel bug
Nov 19 21:29:46 bazzite kwin_wayland[2537]: kwin_wayland_drm: Pageflip timed out! This is a kernel bug
```
while debugging #650, so the two might be related. 

You did say:
> Seemingly at random, 

what is the rough repro rate here? I might need to ask you to turn some debug knobs to get more data, and this would help figure out how. I don't want to put significant perf-reducing or extra-power-consumption changes on you if it means running them for days on end.

**Comment by MeguminSama** [comment]
Thanks - I haven't found any way to reproduce it so far unfortunately. Sometimes it'll happen daily, sometimes not at all, no seeming pattern between them.

I'm happy to turn on debugging stuff, just let me know what to do, and I can send more logs whenever the issue happens :)

**Comment by Zerwin** [comment]
I am also having this issue. A bit of info about my system:

```
Operating System: EndeavourOS 
KDE Plasma Version: 6.2.4
KDE Frameworks Version: 6.8.0
Qt Version: 6.8.0
Kernel Version: 6.12.1-arch1-1 (64-bit)
Graphics Platform: Wayland
Processors: 12 × AMD Ryzen 5 3600X 6-Core Processor
Memory: 15,5 GiB of RAM
Graphics Processor: NVIDIA GeForce RTX 3070/PCIe/SSE2
```
As for repro rate, I have it every few days. And it also isn't always on the same monitor, I have 3 monitors attached, with a mix of HDMI and DP, and by now every monitor was affected at least once by this bug. If it happens again I will provide a nvidia bug report as soon as I can.
One thing I also noticed is that the screen froze exactly 1 second before the kernel log lines. I know this because the clock on my monitor conveniently froze, making it easy to compare.

**Comment by Marnnite** [comment]
I also have this issue.

**NVIDIA Open GPU Kernel Modules Version**
`nvidia-open-dkms 565.57.01-2`

**Operating System and Version**
`Arch Linux x86_64`

**Kernel Release**
`Linux pc 6.12.1-arch1-1 #1 SMP PREEMPT_DYNAMIC Fri, 22 Nov 2024 16:04:27 +0000 x86_64 GNU/Linux`

**Hardware: GPU**
`GPU 0: NVIDIA GeForce GTX 1660 SUPER (UUID: GPU-cf667222-685b-de84-42b1-e446593243a8)`

[nvidia-bug-report.log.gz](https://github.com/user-attachments/files/18029346/nvidia-bug-report.log.gz)

**dmsg**
`
[27236.924270] NVRM: nvAssertFailedNoLog: Assertion failed: CliGetEventInfo(rpc_params->hClient, rpc_params->hEvent, &pEvent) @ kernel_gsp.c:462
[27236.924276] NVRM: _kgspProcessRpcEvent: Failed to process received event 0x1003 (POST_EVENT) from GPU0: status=0x57
`

**systemd journal**
`
Dec 05 22:00:57 pc kernel: NVRM: nvAssertFailedNoLog: Assertion failed: CliGetEventInfo(rpc_params->hClient, rpc_params->hEvent, &pEvent) @ kernel_gsp.c:462
Dec 05 22:00:57 pc kernel: NVRM: _kgspProcessRpcEvent: Failed to process received event 0x1003 (POST_EVENT) from GPU0: status=0x57
Dec 05 22:01:04 pc kwin_wayland[2483]: kwin_wayland_drm: Pageflip timed out! This is a kernel bug
Dec 05 22:01:09 pc kwin_wayland[2483]: kwin_wayland_drm: Pageflip timed out! This is a kernel bug
Dec 05 22:01:14 pc kwin_wayland[2483]: kwin_wayland_drm: Pageflip timed out! This is a kernel bug
Dec 05 22:01:24 pc kwin_wayland[2483]: kwin_wayland_drm: Pageflip timed out! This is a kernel bug
Dec 05 22:01:29 pc kwin_wayland[2483]: kwin_wayland_drm: Pageflip timed out! This is a kernel bug
Dec 05 22:01:34 pc kwin_wayland[2483]: kwin_wayland_drm: Pageflip timed out! This is a kernel bug
`

This happens every so often and usually when watching Youtube, I have 2 monitors, connected with DP and HDMI, sometimes only one of them will freeze, sometimes both.

**Comment by Exotic0015** [comment]
The issue is still present on `565.77`.

**Comment by Zerwin** [comment]
I have an nvidia-bug-report now after it happened on my main display again. What would be the best way to provide this file ? I would rather not upload a file with that much data about my private PC to github. Is there an email or something where I could send it to ?

**Comment by tired-runner** [comment]
I've also observed the same issue, though I haven't seen it in around one and half weeks now. Its happened twice, and while watching youtube both times.  Using 3 monitors connected through displayport on a 3080

**Comment by C0rn3j** [comment]
565.77, RTX 4090, Arch Linux, 6.12.3.

2x DP monitors + 1x HDMI TV, which annoying forces screen reconnects at times, so that may or may not be relevant.


My occurrences are also pretty sparse - 

Nov 24 with some 565 beta driver:
```
[267363.354004] NVRM: nvAssertFailedNoLog: Assertion failed: CliGetEventInfo(rpc_params->hClient, rpc_params->hEvent, &pEvent) @ kernel_gsp.c:462
[267363.354015] NVRM: _kgspProcessRpcEvent: Failed to process received event 0x1003 (POST_EVENT) from GPU0: status=0x57
```

Dec 9 with 565.77: 
```
[148301.259066] NVRM: nvAssertFailedNoLog: Assertion failed: CliGetEventInfo(rpc_params->hClient, rpc_params->hEvent, &pEvent) @ kernel_gsp.c:462
[148301.259075] NVRM: _kgspProcessRpcEvent: Failed to process received event 0x1003 (POST_EVENT) from GPU0: status=0x57
```

![Image](https://github.com/user-attachments/assets/0ebcbcbc-5118-492a-8f1c-3eeb7d3f2faa)

**Comment by oDisMal** [comment]
Hi just confirming issue still persists. Aver a week now one random monitor will freeze, although very typically its a secondary monitor (if not everytime). 
Ryzen 5900x
RTX 2080 - Driver Version: 565.77
Arch 6.12.3-arch1-1
KDE Wayland 

Dec 09 18:38:06 bigbro kwin_wayland[2039]: kwin_wayland_drm: Pageflip timed out! This is a kernel bug
Dec 09 18:38:07 bigbro kwin_wayland[2039]: kwin_wayland_drm: atomic commit failed: Invalid argument

**Comment by ClutchFred** [comment]
I'm also experiencing this issue. Switching TTYs unfreezes the display. It happens most of the time while gaming (Minecraft), and it typically occurs 2-3 times in a short period. After that, everything runs fine, sometimes for several hours.

Does anyone know of a version where this bug is not present?

**Comment by ptr1337** [comment]
> I'm also experiencing this issue. Switching TTYs unfreezes the display. It happens most of the time while gaming (Minecraft), and it typically occurs 2-3 times in a short period. After that, everything runs fine, sometimes for several hours.
> 
> Does anyone know of a version where this bug is not present?

I think the 565 beta did not have the issue. Please provide a nvidia-bug-report.sh to get more information. This is very important, so that the developers can track it better down.

**Comment by butztill** [comment]
Hi, I also have this issue. I have a HDMI and DP Screen connected as well and am using Nvidia Open Kernel Modules 565.77

Here's the logs:
`Dez 17 19:57:53 butztill-PC kernel: NVRM: nvAssertFailedNoLog: Assertion failed: CliGetEventInfo(rpc_params->hClient, rpc_params->hEvent, &pEvent) @ kernel_gsp.c:462
Dez 17 19:57:53 butztill-PC kernel: NVRM: _kgspProcessRpcEvent: Failed to process received event 0x1003 (POST_EVENT) from GPU0: status=0x57
Dez 17 19:57:58 butztill-PC kwin_wayland[1953]: kwin_wayland_drm: Pageflip timed out! This is a kernel bug
Dez 17 19:58:03 butztill-PC kwin_wayland[1953]: kwin_wayland_drm: Pageflip timed out! This is a kernel bug
Dez 17 19:58:08 butztill-PC kwin_wayland[1953]: kwin_wayland_drm: Pageflip timed out! This is a kernel bug
Dez 17 19:58:13 butztill-PC kwin_wayland[1953]: kwin_wayland_drm: Pageflip timed out! This is a kernel bug
Dez 17 19:58:18 butztill-PC kwin_wayland[1953]: kwin_wayland_drm: Pageflip timed out! This is a kernel bug
Dez 17 19:58:23 butztill-PC kwin_wayland[1953]: kwin_wayland_drm: Pageflip timed out! This is a kernel bug
Dez 17 19:58:29 butztill-PC wireplumber[2009]: wp-event-dispatcher: <WpAsyncEventHook:0x5be669e88210> failed: <WpSiStandardLink:0x5be66a263da0> link failed: some node was destroyed before the link was created
Dez 17 19:58:29 butztill-PC wireplumber[2009]: wp-event-dispatcher: <WpAsyncEventHook:0x5be669e88210> failed: <WpSiStandardLink:0x5be66a00d850> link failed: some node was destroyed before the link was created
Dez 17 19:58:42 butztill-PC vesktop[2655]: 'loop->recurse > 0' failed at ../pipewire/src/pipewire/thread-loop.c:425 pw_thread_loop_wait()
Dez 17 19:58:42 butztill-PC kded6[2070]: Service  ":1.276" unregistered
Dez 17 19:58:43 butztill-PC kwin_wayland[1953]: kwin_wayland_drm: Pageflip timed out! This is a kernel bug
Dez 17 19:58:47 butztill-PC kernel: [drm:nv_drm_atomic_commit [nvidia_drm]] *ERROR* [nvidia-drm] [GPU ID 0x00000100] Flip event timeout on head 1
Dez 17 19:58:48 butztill-PC kwin_wayland[1953]: kwin_wayland_drm: Pageflip timed out! This is a kernel bug
Dez 17 19:58:50 butztill-PC kernel: [drm:nv_drm_atomic_commit [nvidia_drm]] *ERROR* [nvidia-drm] [GPU ID 0x00000100] Flip event timeout on head 1`

**Comment by seadra** [comment]
Also confirming here, using Arch Linux, with nvidia-open-dkms 565.77-2, linux 6.6.68-1-lts
Main display is connected via DP, secondary display is HDMI.

**Comment by apo-egix** [comment]
the error presists with linux 6.6.69-1-lts and nvidia-open-dkms 565.77-3

**Comment by janost** [comment]
I'm experiencing exactly the same issue for weeks on Bazzite with a 4080 Super, running plasma 6.2.5 wayland session.
Driver version: 565.77
Kernel version: 6.12.8-201.bazzite.fc41.x86_64

Happens every few hours, one of my DP displays freezes. Switching to a TTY and back "fixes" the issue.

**Comment by brunoliveiraaraujo** [comment]
I'm also having the same issue on Nobara 41, KDE Plasma (Wayland) with a 4070 Super.

2 monitors on DP, the secondary monitor freezes randomly.
Sometimes switching to TTY fixes it, other times freezes the whole system.

Currently driver is 565.77, and Kernel is 6.12.9-202.nobara.fc41.x86_64, but I also had experienced this on previous versions and on other machines for about a year now, both with a 1660 Ti and a 3060.

Previously the only workaround that solved this for me, was switching from KDE Plasma Wayland to X11. But sadly, in Nobara 41 support for X11 was dropped. I might have to switch to GNOME or another desktop environment to see if it solves this problem.

**Comment by gilvbp** [comment]
> I'm also having the same issue on Nobara 41, KDE Plasma (Wayland) with a 4070 Super.
> 
> 2 monitors on DP, the secondary monitor freezes randomly.
> Sometimes switching to TTY fixes it, other times freezes the whole system.
> 
> Currently driver is 565.77, and Kernel is 6.12.9-202.nobara.fc41.x86_64, but I also had experienced this on previous versions and on other machines for about a year now, both with a 1660 Ti and a 3060.
> 
> Previously the only workaround that solved this for me, was switching from KDE Plasma Wayland to X11. But sadly, in Nobara 41 support for X11 was dropped. I might have to switch to GNOME or another desktop environment to see if it solves this problem.

On cosmic-epoch is working fine.

**Comment by musabagriyanik** [comment]
CachyOS
KDE Plasma 6.2.5 Wayland
Linux 6.12
NVIDIA 565.77

I have one display and had this three times. Two of them was recovered by switching to another TTY, waiting a little (not longer than a minute) and coming back. In one case I had to reboot system after waiting a few minutes, it didn't recover.

**Comment by gilvbp** [comment]
Is this issue is fixed on 570.86?

**Comment by Exotic0015** [comment]
Nope, it's still present on `570.86.16`.

**Comment by Exotic0015** [comment]
@mtijanic Sorry to bother, but has there been any internal progress on this bug?
It's been almost three months since the first report and the issue is quite severe

**Comment by virtuous-byte** [comment]
I started to use 570 drivers even before they were officially released and I wanted to wait a few weeks before commenting here. I'm not encountering this bug anymore, I can't say it's fixed as it was already something happens rarely, maybe it was just my luck or it's actually not present anymore.

**Comment by amrit1711** [comment]
Please share fresh bug report with driver 570.86.16 if issue still persists.

**Comment by Exotic0015** [comment]
> Please share fresh bug report with driver 570.86.16 if issue still persists.

[nvidia-bug-report.log.gz](https://github.com/user-attachments/files/18758650/nvidia-bug-report.log.gz)

**Comment by amrit1711** [comment]
Thanks @butztill @Exotic0015 
It would be good to know if you have reliable repro steps which I can refer to reproduce issue locally.
Thanks again for all the help.

**Comment by katanacrimson** [comment]
Chiming in as someone previously affected by this bug - I've since updated to 570.86.16, and have yet to have it occur again.  Literally just updated from rolled-back drivers however (yesterday) so there's not been much opportunity for me to run into this yet.

Unfortunately, it's *extremely* hard for me to deliberately trigger.  That said, almost every instance I have encountered it has been when I was alt-tabbing between a windowed-fullscreen game on one monitor and Discord on my other monitor.

I am currently (and was, when experiencing this issue) running KDE6 on Arch using Wayland.  This issue also seemed to occur more frequently when I was playing Factorio (native Linux build, not Proton), but that might be observation bias and I wouldn't lend it much credence.

Again, please note that this is only when I've *noticed* the bug emerge. Typically, I notice the bug within 1-3 minutes based on past review of `dmesg` output.

**Comment by butztill** [comment]
> Thanks @butztill @Exotic0015 
> It would be good to know if you have reliable repro steps which I can refer to reproduce issue locally.
> Thanks again for all the help.

Hi! Thanks for your help. It's very hard to reproduce the bug since it seemingly happens at random. The screen just freezes and for me there seems to be no pattern behind it.

**Comment by cm-pony** [comment]
Happened 3 times for me yesterday. At 13:55 I was working (running jetbrains idea and dbforge) and two other times I was playing Minecraft. It's looks like it's completely random, switching to tty and back "fixes" the issue.

I have 3 monitors, all connected via DP from left to right:
1. Vertical running at 3840x2160@60hz with dpi scale 175% (benq)
2. 2560x1440@240hz with 100% dpi scale (lg) - primary
3. 2560x1440@144hz with 100% dpi scale(acer)

Freezing **always** occur on 3rd monitor (2560x1440@144hz (acer))

It's probably worth mentioning - my main sound output is also via 3rd monitor 

My pc usually running all day so 3 times doesn't look like too often but it _feels like_ gaming accelerate this but it's not the cause.

```
фев 11 13:55:35 rainbowdash kernel: NVRM: nvAssertFailedNoLog: Assertion failed: CliGetEventInfo(rpc_params->hClient, rpc_params->hEvent, &pEvent) @ kernel_gsp.c:466
фев 11 13:55:35 rainbowdash kernel: NVRM: _kgspProcessRpcEvent: Failed to process received event 0x1003 (POST_EVENT) from GPU0: status=0x57
фев 11 13:55:40 rainbowdash kwin_wayland[1020]: kwin_wayland_drm: Pageflip timed out! This is a kernel bug

фев 11 17:34:35 rainbowdash kernel: NVRM: nvAssertFailedNoLog: Assertion failed: CliGetEventInfo(rpc_params->hClient, rpc_params->hEvent, &pEvent) @ kernel_gsp.c:466
фев 11 17:34:35 rainbowdash kernel: NVRM: _kgspProcessRpcEvent: Failed to process received event 0x1003 (POST_EVENT) from GPU0: status=0x57
фев 11 17:34:40 rainbowdash kwin_wayland[1020]: kwin_wayland_drm: Pageflip timed out! This is a kernel bug
фев 11 17:34:45 rainbowdash kwin_wayland[1020]: kwin_wayland_drm: Pageflip timed out! This is a kernel bug

фев 11 20:37:26 rainbowdash kernel: NVRM: nvAssertFailedNoLog: Assertion failed: CliGetEventInfo(rpc_params->hClient, rpc_params->hEvent, &pEvent) @ kernel_gsp.c:466
фев 11 20:37:26 rainbowdash kernel: NVRM: _kgspProcessRpcEvent: Failed to process received event 0x1003 (POST_EVENT) from GPU0: status=0x57
фев 11 20:37:31 rainbowdash kwin_wayland[1020]: kwin_wayland_drm: Pageflip timed out! This is a kernel bug

```

**Comment by FineWolf** [comment]
Just reproduced on my system. One of three monitors froze while OBS was running on that monitor:

```
Feb 14 10:32:31 WMSPC kernel: NVRM: nvAssertFailedNoLog: Assertion failed: CliGetEventInfo(rpc_params->hClient, rpc_params->hEvent, &pEvent) @ kernel_gsp.c:466
Feb 14 10:32:31 WMSPC kernel: NVRM: _kgspProcessRpcEvent: Failed to process received event 0x1003 (POST_EVENT) from GPU0: status=0x57
Feb 14 10:32:32 WMSPC kwin_wayland[3415]: kwin_wayland_drm: Pageflip timed out! This is a bug in the nvidia-drm kernel driver
```

Nvidia Bug Report: [nvidia-bug-report.log.gz](https://github.com/user-attachments/files/18801491/nvidia-bug-report.log.gz)

Relevant Arch Linux packages:
```
egl-wayland 4:1.1.17-1
lib32-nvidia-utils 570.86.16-1
libva-nvidia-driver 0.0.13-1
linux-firmware 20250109.7673dffd-1
linux-zen 6.13.2.zen1-1
nvidia-open-dkms 570.86.16-2
```

**Comment by cbmason** [comment]
Another occurrence here.  Happens while playing youtube or gaming, one monitor of a 3 monitor setup freezes.

Nobara 40
KDE Plasma 6.2.5
Linux kernel 6.12 
RTX 4070ti, driver v565.77

Attempted a workaround described elsewhere of adding "nvidia.NVreg_EnableGpuFirmware=0" to kernel boot params, with no success (apparently this does nothing in new drivers?)
Workaround of switching TTYs back and forth does "unstick" it.

[nvidia-bug-report.log.gz](https://github.com/user-attachments/files/18805057/nvidia-bug-report.log.gz)

**Comment by ptr1337** [comment]
> Another occurrence here. Happens while playing youtube or gaming, one monitor of a 3 monitor setup freezes.
> 
> Nobara 40 KDE Plasma 6.2.5 Linux kernel 6.12 RTX 4070ti, driver v565.77
> 
> Attempted a workaround described elsewhere of adding "nvidia.NVreg_EnableGpuFirmware=0" to kernel boot params, with no success (apparently this does nothing in new drivers?) Workaround of switching TTYs back and forth does "unstick" it.
> 
> [nvidia-bug-report.log.gz](https://github.com/user-attachments/files/18805057/nvidia-bug-report.log.gz)

You need to use the closed module to disable the gsp firmware.

**Comment by RevoSucks** [comment]
Happens here too. Running Nvidia driver version 565.77 .

Operating System: Fedora Linux 41
KDE Plasma Version: 6.3.1
KDE Frameworks Version: 6.11.0
Qt Version: 6.8.2
Kernel Version: 6.12.15-200.fc41.x86_64 (64-bit)
Graphics Platform: Wayland
Processors: 64 × AMD Ryzen Threadripper 3970X 32-Core Processor
Memory: 125.7 GiB of RAM
Graphics Processor: NVIDIA GeForce RTX 4090/PCIe/SSE2
Manufacturer: Gigabyte Technology Co., Ltd.
Product Name: TRX40 AORUS PRO WIFI
System Version: -CF

**Comment by Exotic0015** [comment]
Still on `570.124.04`, fresh bug report: [nvidia-bug-report.log.gz](https://github.com/user-attachments/files/19015936/nvidia-bug-report.log.gz)

**Comment by MrLixam** [comment]
Experiencing the same issue on driver version `570.124.04`

some info on my system
```
OS: EndeavourOS x86_64
Kernel: Linux 6.13.5-arch1-1
DE: KDE Plasma 6.3.2
WM: KWin (Wayland)
CPU: AMD Ryzen 7 5800X (16) @ 4.85 GHz
GPU: NVIDIA GeForce RTX 2080 SUPER [Discrete]
Memory: 31.26 GiB
```

I've got 3 screens all at 1080p, all with different refresh rates
what i've noted about this bug on my system:
- the freeze always happens on the same monitor
- I haven't had it occur on small uptimes, always at 12h to 15h of uptime, though that probably isn't very relevant
- Turning off the frozen display or disabling it will freeze the other 2 displays, the system is still functional, as I can connect via ssh to the system with my phone and I also can blindly type commands to shutdown the system
- switching to a tty will fix the issue ~50% of the time
- the only way i've found to fix it reliably is to kill kwin-wayland or logging out (effectively killing kwin as well I'm guessing)
- The issue doesn't seem to be linked to any specific app, but I can't reliably say that, as steam or firefox where running when each freeze has happened currently

I've been told to disable GSP by creating the `/etc/modprobe.d/nvidia.conf` file and adding this line to it: `options nvidia NVreg_EnableGpuFirmware=0`, checking modprobe, the option is seemingly used, but does not fix the issue, maybe i've set it incorrectly?
will try to provide a log when the issue reoccurs

**Comment by C0rn3j** [comment]
@MrLixam 570.124.04 has a new one - https://forums.developer.nvidia.com/t/2nd-monitor-frozen-recent-freezing/325588

**Comment by MrLixam** [comment]
@C0rn3j Ah thank you, I hadn't seen this thread on the forum yet, seems like it is the same issue as mine.
Just checked and I am using `nvidia-dkms` not `nvidia-open-dkms` on my system. Would it still be useful to share my log file on this thread or is my issue unrelated to this repo? I'm not well informed on nvidia's driver repo structure.

**Comment by C0rn3j** [comment]
> is my issue unrelated to this repo? 

https://github.com/NVIDIA/open-gpu-kernel-modules?tab=readme-ov-file#how-to-report-issues

This is the repo for issues *exclusive* to the open driver

**Comment by MrLixam** [comment]
Okay, thanks for the information, will go add to the forum post

**Comment by PandorasFox** [comment]
[nvidia-bug-report.log.gz](https://github.com/user-attachments/files/19411650/nvidia-bug-report.log.gz)

happened to me on arch linux w/ kde, approximately when I ended a discord screencapture via closing the window that was captured (unsure exactly how the timing there lines up).

relevant packages:

```
pacman -Q | grep -e nvidia -e kwin -e egl
egl-gbm 1.1.2-1
egl-wayland 4:1.1.18-1
egl-x11 1.0.0-1
eglexternalplatform 1.2-2
freeglut 3.6.0-1
gegl 0.4.56-1
kwin 6.3.3.1-1
kwindowsystem 6.12.0-1
lib32-nvidia-utils 570.124.04-1
libva-nvidia-driver 0.0.13-1
nvidia-open 570.124.04-4
nvidia-utils 570.124.04-1
```

**Comment by Chapien** [comment]
Still happening for me. 

```shell
 kinfo
Operating System: Arch Linux
KDE Plasma Version: 6.3.3
KDE Frameworks Version: 6.12.0
Qt Version: 6.8.2
Kernel Version: 6.13.8-arch1-1 (64-bit)
Graphics Platform: Wayland
Processors: 16 × AMD Ryzen 7 5800X3D 8-Core Processor
Memory: 31.2 GiB of RAM
Graphics Processor: NVIDIA GeForce RTX 2060 SUPER
```

relevant packages
```shell
 pacman -Q | grep -e nvidia -e kwin -e egl
egl-gbm 1.1.2.1-1
egl-wayland 4:1.1.18-1
egl-x11 1.0.0-1
eglexternalplatform 1.2-2
freeglut 3.6.0-1
gegl-git 0.4.59.r10976.ea858b2e2-1
kwin 6.3.3.1-1
kwindowsystem 6.12.0-1
kwindowsystem5 5.116.0-1
lib32-nvidia-utils 570.133.07-1
nvidia-open-dkms 570.133.07-1
nvidia-settings 570.133.07-1
nvidia-utils 570.133.07-1
vk-hdr-layer-kwin6-git r41.7c0553d-1
```

output of sudo dmesg
```shell
[ 3134.565514] NVRM: nvAssertFailedNoLog: Assertion failed: CliGetEventInfo(rpc_params->hClient, rpc_params->hEvent, &pEvent) @ kernel_gsp.c:466
[ 3134.565523] NVRM: _kgspProcessRpcEvent: Failed to process received event 0x1003 (POST_EVENT) from GPU0: status=0x57
[ 3321.084902] [drm:nv_drm_atomic_commit [nvidia_drm]] *ERROR* [nvidia-drm] [GPU ID 0x00000700] Flip event timeout on head 2
[ 3324.284888] [drm:nv_drm_atomic_commit [nvidia_drm]] *ERROR* [nvidia-drm] [GPU ID 0x00000700] Flip event timeout on head 2
[ 3343.791868] traps: ThreadPoolForeg[23128] trap int3 ip:56855c5a6ce5 sp:7190a97f50f0 error:0 in vesktop[6121ce5,568558476000+897c000]
[ 5274.506963] NVRM: nvAssertFailedNoLog: Assertion failed: CliGetEventInfo(rpc_params->hClient, rpc_params->hEvent, &pEvent) @ kernel_gsp.c:466
[ 5274.506971] NVRM: _kgspProcessRpcEvent: Failed to process received event 0x1003 (POST_EVENT) from GPU0: status=0x57
[ 5288.179888] [drm:nv_drm_atomic_commit [nvidia_drm]] *ERROR* [nvidia-drm] [GPU ID 0x00000700] Flip event timeout on head 0
[ 5291.379873] [drm:nv_drm_atomic_commit [nvidia_drm]] *ERROR* [nvidia-drm] [GPU ID 0x00000700] Flip event timeout on head 0
```

output of journalctl --user-unit plasma-kwin_wayland --boot 0
```shell
Mar 27 09:02:59 claire-pc kwin_wayland[1148]: kf.windowsystem: static bool KX11Extras::mapViewport() may only be used on X11
Mar 27 09:03:34 claire-pc kwin_wayland[1148]: kwin_xwl: Could not create a source from 0x738720005c30 0
Mar 27 09:04:15 claire-pc kwin_wayland[1148]: kwin_scene_opengl: 0x502: GL_INVALID_OPERATION error generated.
Mar 27 09:04:15 claire-pc kwin_wayland[1148]: kwin_scene_opengl: 0x502: GL_INVALID_OPERATION error generated.
Mar 27 09:04:15 claire-pc kwin_wayland[1148]: kwin_scene_opengl: 0x502: GL_INVALID_OPERATION error generated.
Mar 27 09:04:15 claire-pc kwin_wayland[1148]: kwin_scene_opengl: 0x502: GL_INVALID_OPERATION error generated.
Mar 27 09:04:15 claire-pc kwin_wayland[1148]: kwin_scene_opengl: 0x502: GL_INVALID_OPERATION error generated.
Mar 27 09:04:15 claire-pc kwin_wayland[1148]: kwin_scene_opengl: 0x502: GL_INVALID_OPERATION error generated.
Mar 27 09:04:15 claire-pc kwin_wayland[1148]: kwin_scene_opengl: 0x502: GL_INVALID_OPERATION error generated.
Mar 27 09:04:15 claire-pc kwin_wayland[1148]: kwin_scene_opengl: 0x502: GL_INVALID_OPERATION error generated.
Mar 27 09:04:15 claire-pc kwin_wayland[1148]: kwin_scene_opengl: 0x502: GL_INVALID_OPERATION error generated.
Mar 27 09:04:16 claire-pc kwin_wayland[1148]: kwin_scene_opengl: 0x502: GL_INVALID_OPERATION error generated.
Mar 27 09:04:16 claire-pc kwin_wayland[1148]: kwin_scene_opengl: 0x502: GL_INVALID_OPERATION error generated.
Mar 27 09:04:16 claire-pc kwin_wayland[1148]: kwin_scene_opengl: 0x502: GL_INVALID_OPERATION error generated.
Mar 27 09:04:16 claire-pc kwin_wayland[1148]: kwin_scene_opengl: 0x502: GL_INVALID_OPERATION error generated.
Mar 27 09:04:16 claire-pc kwin_wayland[1148]: kwin_scene_opengl: 0x502: GL_INVALID_OPERATION error generated.
Mar 27 09:04:16 claire-pc kwin_wayland[1148]: kwin_scene_opengl: 0x502: GL_INVALID_OPERATION error generated.
Mar 27 09:04:50 claire-pc kwin_wayland[1148]: kwin_scene_opengl: 0x502: GL_INVALID_OPERATION error generated.
Mar 27 09:04:50 claire-pc kwin_wayland[1148]: kwin_scene_opengl: 0x502: GL_INVALID_OPERATION error generated.
Mar 27 09:04:50 claire-pc kwin_wayland[1148]: kwin_scene_opengl: 0x502: GL_INVALID_OPERATION error generated.
Mar 27 09:04:51 claire-pc kwin_wayland[1148]: kwin_scene_opengl: 0x502: GL_INVALID_OPERATION error generated.
Mar 27 09:04:51 claire-pc kwin_wayland[1148]: kwin_scene_opengl: 0x502: GL_INVALID_OPERATION error generated.
Mar 27 09:04:51 claire-pc kwin_wayland[1148]: kwin_scene_opengl: 0x502: GL_INVALID_OPERATION error generated.
Mar 27 09:04:51 claire-pc kwin_wayland[1148]: kwin_scene_opengl: 0x502: GL_INVALID_OPERATION error generated.
Mar 27 09:13:19 claire-pc kwin_wayland[1148]: kwin_scene_opengl: 0x502: GL_INVALID_OPERATION error generated.
Mar 27 09:13:19 claire-pc kwin_wayland[1148]: kwin_scene_opengl: 0x502: GL_INVALID_OPERATION error generated.
Mar 27 09:13:19 claire-pc kwin_wayland[1148]: kwin_scene_opengl: 0x502: GL_INVALID_OPERATION error generated.
Mar 27 09:13:19 claire-pc kwin_wayland[1148]: kwin_scene_opengl: 0x502: GL_INVALID_OPERATION error generated.
Mar 27 09:13:19 claire-pc kwin_wayland[1148]: kwin_scene_opengl: 0x502: GL_INVALID_OPERATION error generated.
Mar 27 09:13:19 claire-pc kwin_wayland[1148]: kwin_scene_opengl: 0x502: GL_INVALID_OPERATION error generated.
Mar 27 09:13:19 claire-pc kwin_wayland[1148]: kwin_scene_opengl: 0x502: GL_INVALID_OPERATION error generated.
Mar 27 09:13:19 claire-pc kwin_wayland[1148]: kwin_scene_opengl: 0x502: GL_INVALID_OPERATION error generated.
Mar 27 09:13:19 claire-pc kwin_wayland[1148]: kwin_scene_opengl: 0x502: GL_INVALID_OPERATION error generated.
Mar 27 09:13:19 claire-pc kwin_wayland[1148]: kwin_scene_opengl: 0x502: GL_INVALID_OPERATION error generated.
Mar 27 09:13:19 claire-pc kwin_wayland[1148]: kwin_scene_opengl: 0x502: GL_INVALID_OPERATION error generated.
Mar 27 09:13:19 claire-pc kwin_wayland[1148]: kwin_scene_opengl: 0x502: GL_INVALID_OPERATION error generated.
Mar 27 09:13:19 claire-pc kwin_wayland[1148]: kwin_scene_opengl: 0x502: GL_INVALID_OPERATION error generated.
Mar 27 09:13:19 claire-pc kwin_wayland[1148]: kwin_scene_opengl: 0x502: GL_INVALID_OPERATION error generated.
Mar 27 09:13:57 claire-pc kwin_wayland[1148]: kwin_wayland_drm: Pageflip timed out! This is a bug in the nvidia-drm kernel drive
```

Other relevant info: Only one monitor freezes. Others run perfectly fine, but only a relog fixes it. Restarting is not necessary, only relogging. KDE seems adamant that it's an nvidia side issue. Some people equate it with monitors waking up from sleep, but it happens _randomly_ for me. Sometimes I can go all day without it happening, other times its constant. Is there a workaround? Any sign of a fix?

**Comment by RevoSucks** [comment]
> Still happening for me.
> 
>  kinfo
> Operating System: Arch Linux
> KDE Plasma Version: 6.3.3
> KDE Frameworks Version: 6.12.0
> Qt Version: 6.8.2
> Kernel Version: 6.13.8-arch1-1 (64-bit)
> Graphics Platform: Wayland
> Processors: 16 × AMD Ryzen 7 5800X3D 8-Core Processor
> Memory: 31.2 GiB of RAM
> Graphics Processor: NVIDIA GeForce RTX 2060 SUPER
> 
> relevant packages
> 
>  pacman -Q | grep -e nvidia -e kwin -e egl
> egl-gbm 1.1.2.1-1
> egl-wayland 4:1.1.18-1
> egl-x11 1.0.0-1
> eglexternalplatform 1.2-2
> freeglut 3.6.0-1
> gegl-git 0.4.59.r10976.ea858b2e2-1
> kwin 6.3.3.1-1
> kwindowsystem 6.12.0-1
> kwindowsystem5 5.116.0-1
> lib32-nvidia-utils 570.133.07-1
> nvidia-open-dkms 570.133.07-1
> nvidia-settings 570.133.07-1
> nvidia-utils 570.133.07-1
> vk-hdr-layer-kwin6-git r41.7c0553d-1
> 
> output of sudo dmesg
> 
> [ 3134.565514] NVRM: nvAssertFailedNoLog: Assertion failed: CliGetEventInfo(rpc_params->hClient, rpc_params->hEvent, &pEvent) @ kernel_gsp.c:466
> [ 3134.565523] NVRM: _kgspProcessRpcEvent: Failed to process received event 0x1003 (POST_EVENT) from GPU0: status=0x57
> [ 3321.084902] [drm:nv_drm_atomic_commit [nvidia_drm]] *ERROR* [nvidia-drm] [GPU ID 0x00000700] Flip event timeout on head 2
> [ 3324.284888] [drm:nv_drm_atomic_commit [nvidia_drm]] *ERROR* [nvidia-drm] [GPU ID 0x00000700] Flip event timeout on head 2
> [ 3343.791868] traps: ThreadPoolForeg[23128] trap int3 ip:56855c5a6ce5 sp:7190a97f50f0 error:0 in vesktop[6121ce5,568558476000+897c000]
> [ 5274.506963] NVRM: nvAssertFailedNoLog: Assertion failed: CliGetEventInfo(rpc_params->hClient, rpc_params->hEvent, &pEvent) @ kernel_gsp.c:466
> [ 5274.506971] NVRM: _kgspProcessRpcEvent: Failed to process received event 0x1003 (POST_EVENT) from GPU0: status=0x57
> [ 5288.179888] [drm:nv_drm_atomic_commit [nvidia_drm]] *ERROR* [nvidia-drm] [GPU ID 0x00000700] Flip event timeout on head 0
> [ 5291.379873] [drm:nv_drm_atomic_commit [nvidia_drm]] *ERROR* [nvidia-drm] [GPU ID 0x00000700] Flip event timeout on head 0
> 
> output of journalctl --user-unit plasma-kwin_wayland --boot 0
> 
> Mar 27 09:02:59 claire-pc kwin_wayland[1148]: kf.windowsystem: static bool KX11Extras::mapViewport() may only be used on X11
> Mar 27 09:03:34 claire-pc kwin_wayland[1148]: kwin_xwl: Could not create a source from 0x738720005c30 0
> Mar 27 09:04:15 claire-pc kwin_wayland[1148]: kwin_scene_opengl: 0x502: GL_INVALID_OPERATION error generated.
> Mar 27 09:04:15 claire-pc kwin_wayland[1148]: kwin_scene_opengl: 0x502: GL_INVALID_OPERATION error generated.
> Mar 27 09:04:15 claire-pc kwin_wayland[1148]: kwin_scene_opengl: 0x502: GL_INVALID_OPERATION error generated.
> Mar 27 09:04:15 claire-pc kwin_wayland[1148]: kwin_scene_opengl: 0x502: GL_INVALID_OPERATION error generated.
> Mar 27 09:04:15 claire-pc kwin_wayland[1148]: kwin_scene_opengl: 0x502: GL_INVALID_OPERATION error generated.
> Mar 27 09:04:15 claire-pc kwin_wayland[1148]: kwin_scene_opengl: 0x502: GL_INVALID_OPERATION error generated.
> Mar 27 09:04:15 claire-pc kwin_wayland[1148]: kwin_scene_opengl: 0x502: GL_INVALID_OPERATION error generated.
> Mar 27 09:04:15 claire-pc kwin_wayland[1148]: kwin_scene_opengl: 0x502: GL_INVALID_OPERATION error generated.
> Mar 27 09:04:15 claire-pc kwin_wayland[1148]: kwin_scene_opengl: 0x502: GL_INVALID_OPERATION error generated.
> Mar 27 09:04:16 claire-pc kwin_wayland[1148]: kwin_scene_opengl: 0x502: GL_INVALID_OPERATION error generated.
> Mar 27 09:04:16 claire-pc kwin_wayland[1148]: kwin_scene_opengl: 0x502: GL_INVALID_OPERATION error generated.
> Mar 27 09:04:16 claire-pc kwin_wayland[1148]: kwin_scene_opengl: 0x502: GL_INVALID_OPERATION error generated.
> Mar 27 09:04:16 claire-pc kwin_wayland[1148]: kwin_scene_opengl: 0x502: GL_INVALID_OPERATION error generated.
> Mar 27 09:04:16 claire-pc kwin_wayland[1148]: kwin_scene_opengl: 0x502: GL_INVALID_OPERATION error generated.
> Mar 27 09:04:16 claire-pc kwin_wayland[1148]: kwin_scene_opengl: 0x502: GL_INVALID_OPERATION error generated.
> Mar 27 09:04:50 claire-pc kwin_wayland[1148]: kwin_scene_opengl: 0x502: GL_INVALID_OPERATION error generated.
> Mar 27 09:04:50 claire-pc kwin_wayland[1148]: kwin_scene_opengl: 0x502: GL_INVALID_OPERATION error generated.
> Mar 27 09:04:50 claire-pc kwin_wayland[1148]: kwin_scene_opengl: 0x502: GL_INVALID_OPERATION error generated.
> Mar 27 09:04:51 claire-pc kwin_wayland[1148]: kwin_scene_opengl: 0x502: GL_INVALID_OPERATION error generated.
> Mar 27 09:04:51 claire-pc kwin_wayland[1148]: kwin_scene_opengl: 0x502: GL_INVALID_OPERATION error generated.
> Mar 27 09:04:51 claire-pc kwin_wayland[1148]: kwin_scene_opengl: 0x502: GL_INVALID_OPERATION error generated.
> Mar 27 09:04:51 claire-pc kwin_wayland[1148]: kwin_scene_opengl: 0x502: GL_INVALID_OPERATION error generated.
> Mar 27 09:13:19 claire-pc kwin_wayland[1148]: kwin_scene_opengl: 0x502: GL_INVALID_OPERATION error generated.
> Mar 27 09:13:19 claire-pc kwin_wayland[1148]: kwin_scene_opengl: 0x502: GL_INVALID_OPERATION error generated.
> Mar 27 09:13:19 claire-pc kwin_wayland[1148]: kwin_scene_opengl: 0x502: GL_INVALID_OPERATION error generated.
> Mar 27 09:13:19 claire-pc kwin_wayland[1148]: kwin_scene_opengl: 0x502: GL_INVALID_OPERATION error generated.
> Mar 27 09:13:19 claire-pc kwin_wayland[1148]: kwin_scene_opengl: 0x502: GL_INVALID_OPERATION error generated.
> Mar 27 09:13:19 claire-pc kwin_wayland[1148]: kwin_scene_opengl: 0x502: GL_INVALID_OPERATION error generated.
> Mar 27 09:13:19 claire-pc kwin_wayland[1148]: kwin_scene_opengl: 0x502: GL_INVALID_OPERATION error generated.
> Mar 27 09:13:19 claire-pc kwin_wayland[1148]: kwin_scene_opengl: 0x502: GL_INVALID_OPERATION error generated.
> Mar 27 09:13:19 claire-pc kwin_wayland[1148]: kwin_scene_opengl: 0x502: GL_INVALID_OPERATION error generated.
> Mar 27 09:13:19 claire-pc kwin_wayland[1148]: kwin_scene_opengl: 0x502: GL_INVALID_OPERATION error generated.
> Mar 27 09:13:19 claire-pc kwin_wayland[1148]: kwin_scene_opengl: 0x502: GL_INVALID_OPERATION error generated.
> Mar 27 09:13:19 claire-pc kwin_wayland[1148]: kwin_scene_opengl: 0x502: GL_INVALID_OPERATION error generated.
> Mar 27 09:13:19 claire-pc kwin_wayland[1148]: kwin_scene_opengl: 0x502: GL_INVALID_OPERATION error generated.
> Mar 27 09:13:19 claire-pc kwin_wayland[1148]: kwin_scene_opengl: 0x502: GL_INVALID_OPERATION error generated.
> Mar 27 09:13:57 claire-pc kwin_wayland[1148]: kwin_wayland_drm: Pageflip timed out! This is a bug in the nvidia-drm kernel drive
> 
> Other relevant info: Only one monitor freezes. Others run perfectly fine, but only a relog fixes it. Restarting is not necessary, only relogging. KDE seems adamant that it's an nvidia side issue. Some people equate it with monitors waking up from sleep, but it happens _randomly_ for me. Sometimes I can go all day without it happening, other times its constant. Is there a workaround? Any sign of a fix?

I just do Ctrl+Alt+F4 and then Ctrl+Alt+F2 to effectively hard "restart" the display manager, which fixes the issue every time it happens.

**Comment by Chapien** [comment]
> 
> I just do Ctrl+Alt+F4 and then Ctrl+Alt+F2 to effectively hard "restart" the display manager, which fixes the issue every time it happens.

Does this crash any processes? If it closes a ton of my programs I'd rather just relog to make sure everything is starting properly.

**Comment by RevoSucks** [comment]
I havent noticed any "crashes" while using it. The audio stops, but then it resumes when you Ctrl+Alt+F2.

**Comment by Chapien** [comment]
> I havent noticed any "crashes" while using it. The audio stops, but then it resumes when you Ctrl+Alt+F2.

Good to know -- I ask because restarting plasma shell crashes a ton of programs in the process.

**Comment by Chapien** [comment]
> I havent noticed any "crashes" while using it. The audio stops, but then it resumes when you Ctrl+Alt+F2.

Update for those finding this: ctrl+alt+f2 will put you into an X display. If you're using wayland (like me), you want ctrl+alt+f1.

**Comment by leodip** [comment]
I use Fedora 41, KDE, wayland, nvidia driver 570.133.07, 2 monitors.

I get random freezes. Only 1 monitor freezes. I can't think of a particular trigger, I'm just using the computer and boom, it freezes.

I normally git the hard reset button. But sometimes, I lose work, it sucks!

**Comment by officiallymarky** [comment]
This problem comes and goes (in regards to how frequent it is, it's currently happening constantly).  It's been a long standing issue for like 6 months and getting to the point I am sick of using Linux and it affects my ability to work.kit

**Comment by neomoth** [comment]
Having this issue too regardless of which version of NVIDIA drivers i use including these open drivers. Funnily enough I was looking at this issue thread on my phone when I actually witnessed my right monitor's wallpaper stop moving (using a shader as a wallpaper), which is the first time I've noticed it happening live as usually by time i notice it's already been like 5 minutes since I tried to do anything on the other monitor.

I can confirm that switching to a TTY and back to the wayland session seems to fix it which is very good information to know about as every time before this I had simply resorted to rebooting my system.

Weirdly, `dmesg` is entirely unhelpful in my scenario, with the only relevant info relating to the issue seeming to come from `journalctl`
```
May 04 16:46:26 genesis kwin_wayland[1751]: kwin_wayland_drm: Pageflip timed out! This is a bug in the nvidia-drm kernel driver
May 04 16:46:26 genesis kwin_wayland[1751]: kwin_wayland_drm: Please report this at https://forums.developer.nvidia.com/c/gpu-graphics/linux
May 04 16:46:26 genesis kwin_wayland[1751]: kwin_wayland_drm: With the output of 'sudo dmesg' and 'journalctl --user-unit plasma-kwin_wayland --boot 0'
```
with the only relevant dmesg output being this
```
[253710.129217] fbcon: Taking over console
[253713.167759] [drm:nv_drm_atomic_commit [nvidia_drm]] *ERROR* [nvidia-drm] [GPU ID 0x00000a00] Flip event timeout on head 0
[253716.367449] [drm:nv_drm_atomic_commit [nvidia_drm]] *ERROR* [nvidia-drm] [GPU ID 0x00000a00] Flip event timeout on head 0
[253716.367499] Console: switching to colour frame buffer device 240x67
```
which looks to just be me switching from the wayland session to TTY and back if I'm reading it right.

Issue has been happening randomly on and off for MONTHS, even tried submitting a ticket on the NVIDIA forums but I haven't seen any response yet despite being a month since then.

If there's anything I could send in that could prove helpful in figuring out the issue let me know since I don't know what else I could check or test here.

**Comment by officiallymarky** [comment]
> Having this issue too regardless of which version of NVIDIA drivers i use including these open drivers. Funnily enough I was looking at this issue thread on my phone when I actually witnessed my right monitor's wallpaper stop moving (using a shader as a wallpaper), which is the first time I've noticed it happening live as usually by time i notice it's already been like 5 minutes since I tried to do anything on the other monitor.
> 
> I can confirm that switching to a TTY and back to the wayland session seems to fix it which is very good information to know about as every time before this I had simply resorted to rebooting my system.
> 
> Weirdly, `dmesg` is entirely unhelpful in my scenario, with the only relevant info relating to the issue seeming to come from `journalctl`
> 
> ```
> May 04 16:46:26 genesis kwin_wayland[1751]: kwin_wayland_drm: Pageflip timed out! This is a bug in the nvidia-drm kernel driver
> May 04 16:46:26 genesis kwin_wayland[1751]: kwin_wayland_drm: Please report this at https://forums.developer.nvidia.com/c/gpu-graphics/linux
> May 04 16:46:26 genesis kwin_wayland[1751]: kwin_wayland_drm: With the output of 'sudo dmesg' and 'journalctl --user-unit plasma-kwin_wayland --boot 0'
> ```
> 
> with the only relevant dmesg output being this
> 
> ```
> [253710.129217] fbcon: Taking over console
> [253713.167759] [drm:nv_drm_atomic_commit [nvidia_drm]] *ERROR* [nvidia-drm] [GPU ID 0x00000a00] Flip event timeout on head 0
> [253716.367449] [drm:nv_drm_atomic_commit [nvidia_drm]] *ERROR* [nvidia-drm] [GPU ID 0x00000a00] Flip event timeout on head 0
> [253716.367499] Console: switching to colour frame buffer device 240x67
> ```
> 
> which looks to just be me switching from the wayland session to TTY and back if I'm reading it right.
> 
> Issue has been happening randomly on and off for MONTHS, even tried submitting a ticket on the NVIDIA forums but I haven't seen any response yet despite being a month since then.
> 
> If there's anything I could send in that could prove helpful in figuring out the issue let me know since I don't know what else I could check or test here.

Been having this issue off and on at different frequency in the last 6 months or so.  Some updates it happens rarely (like once every days) then a new update will come out and it happens 2-3 times a day.  It's absolutely maddening this is still happening.  

I can confirm switching tty helps "recover" provided it isn't too far gone, when it happens I frequently get a complete video crash soon after and have to reboot.  

I believe it is related to the flood of nvidia drm pageflip errors in the logs.

**Comment by nyrixx** [comment]
I know while troubleshooting this issue when it has intermittently come up enough to frustrate me given how random it seems to come and go, when I have had time to troubleshooting immediately before the page flip errors fill the journal the errors immediately preceding those are typically these two errors then the usual kwin_wayland_drm: Pageflip:

kernel: NVRM: nvAssertFailedNoLog: Assertion failed: CliGetEventInfo(rpc_params->hClient, rpc_params->hEvent, &pEvent) @ kernel_gsp.c:466
kernel: NVRM: _kgspProcessRpcEvent: Failed to process received event 0x1003 (POST_EVENT) from GPU0: status=0x57

If you search those you will find a few more detailed posts on the nvidia developer forums.
At least in my case this is all relevant to Fedora 42 (KDE Plasma) and I have been having the issues across multiple driver releases since around 09/2024. 

In particular I did find this post where someone replies saying that the fix is available in the current beta branch:
https://forums.developer.nvidia.com/t/pageflip-timed-out-this-is-a-bug-in-the-nvidia-drm-kernel-driver-on-external-display-internal-display-doing-fine/330548

https://www.nvidia.com/en-us/drivers/details/243334/

where in at least a generic sense this line seems to reference what I have been experiencing:
"Fixed an issue that could cause render-offloaded applications using KDE Frameworks 6 to crash."

**Comment by leodip** [comment]
I've just had the issue again.  Left monitor got frozen.  I tried CTRL + ALT + F3, but when I did that, the right monitor was frozen too!  Which left me with no choice but a hard reset.

I can see these logs, not sure if they are related:

```
May 06 14:45:07 ubuntu kernel: [drm:nv_drm_atomic_commit [nvidia_drm]] *ERROR* [nvidia-drm] [GPU ID 0x00000100] Flip event timeou>
May 06 14:45:10 ubuntu kernel: [drm:nv_drm_atomic_commit [nvidia_drm]] *ERROR* [nvidia-drm] [GPU ID 0x00000100] Flip event timeou>
May 06 14:45:13 ubuntu kernel: [drm:nv_drm_atomic_commit [nvidia_drm]] *ERROR* [nvidia-drm] [GPU ID 0x00000100] Flip event timeou>
May 06 14:45:16 ubuntu kernel: [drm:nv_drm_atomic_commit [nvidia_drm]] *ERROR* [nvidia-drm] [GPU ID 0x00000100] Flip event timeou>
May 06 14:45:19 ubuntu kernel: [drm:nv_drm_atomic_commit [nvidia_drm]] *ERROR* [nvidia-drm] [GPU ID 0x00000100] Flip event timeou>
May 06 14:45:22 ubuntu kernel: [drm:nv_drm_atomic_commit [nvidia_drm]] *ERROR* [nvidia-drm] [GPU ID 0x00000100] Flip event timeou>
May 06 14:45:25 ubuntu kernel: [drm:nv_drm_atomic_commit [nvidia_drm]] *ERROR* [nvidia-drm] [GPU ID 0x00000100] Flip event timeou>
May 06 14:45:29 ubuntu kernel: [drm:nv_drm_atomic_commit [nvidia_drm]] *ERROR* [nvidia-drm] [GPU ID 0x00000100] Flip event timeou>
May 06 14:45:32 ubuntu kernel: [drm:nv_drm_atomic_commit [nvidia_drm]] *ERROR* [nvidia-drm] [GPU ID 0x00000100] Flip event timeou>
```

```
nvidia-smi
Tue May  6 14:48:51 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 570.144                Driver Version: 570.144        CUDA Version: 12.8     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce RTX 4060        Off |   00000000:01:00.0  On |                  N/A |
|  0%   46C    P8            N/A  /  120W |     379MiB /   8188MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+
                                                                                         
+-----------------------------------------------------------------------------------------+
| Processes:                                                                              |
|  GPU   GI   CI              PID   Type   Process name                        GPU Memory |
|        ID   ID                                                               Usage      |
|=========================================================================================|
|    0   N/A  N/A            4508      G   /usr/bin/gnome-shell                    340MiB |
|    0   N/A  N/A            4646      G   /usr/bin/Xwayland                         2MiB |
+-----------------------------------------------------------------------------------------+

```

**Comment by eyerust** [comment]
For anyone interested I had this issue since 565 or so using the proprietary driver and it seems the beta driver 575.51.02 I am currently using finally fixed the issue. At least I didn't have the problem anymore for a few weeks now. But as I said this is using the proprietary kernel modules (which also had the problem) and using disabled GSP `nvidia.NVreg_EnableGpuFirmware=0`

**Comment by Edu4rdSHL** [comment]
> For anyone interested I had this issue since 565 or so using the proprietary driver and it seems the beta driver 575.51.02 I am currently using finally fixed the issue. At least I didn't have the problem anymore for a few weeks now. But as I said this is using the proprietary kernel modules (which also had the problem) and using disabled GSP `nvidia.NVreg_EnableGpuFirmware=0`

Disabling GSP fixed the issue on any driver version, so that's not a valid feedback. The problem is with GSP, saying that it was fixed while disabling GSP simply doesn't makes sense.

**Comment by Edu4rdSHL** [comment]
@leodip just disable GSP using the proprietary driver and that's it. There aren't any loss doing that.

**Comment by leodip** [comment]
@Edu4rdSHL Can you tell me what is the meaning of disabling GSP? What would I lose?

**Comment by Edu4rdSHL** [comment]
@leodip you don't lose anything for now, there are even performance gains when doing it. And for disabling GSP you need to use the closed drivers and add this into `/etc/modprobe.d/nvidia.conf`

```
options nvidia NVreg_EnableGpuFirmware=0
```
Technically, GSP should improve things as it leverage processing to the GPU System Processor, but in the current state there are several issues with it, like these crashes. It will become better on next releases for sure.

**Comment by leodip** [comment]
@Edu4rdSHL  Thank you Sir

**Comment by eyerust** [comment]
> > For anyone interested I had this issue since 565 or so using the proprietary driver and it seems the beta driver 575.51.02 I am currently using finally fixed the issue. At least I didn't have the problem anymore for a few weeks now. But as I said this is using the proprietary kernel modules (which also had the problem) and using disabled GSP `nvidia.NVreg_EnableGpuFirmware=0`
> 
> Disabling GSP fixed the issue on any driver version, so that's not a valid feedback. The problem is with GSP, saying that it was fixed while disabling GSP simply doesn't makes sense.

Not true I had the problem even when GSP was disabled.

**Comment by Edu4rdSHL** [comment]
To disable GSP you need to use the proprietary drivers, if you were using the open drivers then you can't disable GSP, even if you have added the options to disable it. So, either:

- You didn't disabled GSP because you were using the open drivers and it can't be disabled there.
- You're experiencing a different bug.

**Comment by I-Percy** [comment]
I am also having the same issue. 

One thing that might be valuable is gathering screen resolution and GPU info from those experiencing the hang. I have a feeling this has to do with a lack of VRAM and high resolution/frame rate. 

I personally have a 3070 paired with one 1440p and one 1080p monitor.

Arch Linux with KDE. 

One more thing: 

I am going to try setting `kwinrc` to:

```
[Wayland]
DirectScanout=false
```

I will test it out, but I do not want this to be a permanent fix as it will impact performance, especially while gaming.

**Comment by oszoou** [comment]
Try using these kernel parameters

`nvidia-drm.modeset=1 nvidia-drm.fbdev=0`

**Comment by officiallymarky** [comment]
> Try using these kernel parameters
> 
> `nvidia-drm.modeset=1 nvidia-drm.fbdev=0`

These don't help

**Comment by gilvbp** [comment]
It's back again on 575.64 using open source.

**Comment by gilvbp** [comment]
> It's back again on 575.64 using open source.

It seems to be fixed on 575.64.3

**Comment by officiallymarky** [comment]
> > It's back again on 575.64 using open source.
> 
> It seems to be fixed on 575.64.3

I am on 575.64.03, just updated today, but it was fixed for me on the last driver.  I haven't had the issue in a few weeks.

**Comment by amrit1711** [comment]
Thanks @gilvbp @officiallymarky for sharing test results.

Awaiting others feedback before closing this thread and our internal bug tracking.

**Comment by Exotic0015** [comment]
Can't reproduce the issue on my end anymore either. Thank you! <3

**Comment by MeguminSama** [comment]
I also haven't had this issue at all recently :)

Nice work!

**Comment by gilvbp** [comment]
> Thanks [@gilvbp](https://github.com/gilvbp) [@officiallymarky](https://github.com/officiallymarky) for sharing test results.
> 
> Awaiting others feedback before closing this thread and our internal bug tracking.

You're welcome! thanks.

**Comment by amrit1711** [comment]
Thank you all for the feedback, I will close this thread and our internal bug tracking.
