### ISSUE TITLE
/sys/class/drm/*/enabled reports “disabled” for enabled monitors

### ISSUE THREAD

**Issue by RMTT** [NVIDIA/open-gpu-kernel-modules#889]
### NVIDIA Open GPU Kernel Modules Version

570.169

### Please confirm this issue does not happen with the proprietary driver (of the same version). This issue tracker is only for bugs specific to the open kernel driver.

- [ ] I confirm that this does not happen with the proprietary driver package.

### Operating System and Version

NixOS

### Kernel Release

6.15.2

### Please confirm you are running a stable release kernel (e.g. not a -rc). We do not accept bug reports for unreleased kernels.

- [x] I am running on a stable kernel release.

### Hardware: GPU

NVIDIA GeForce RTX 5070 Ti Laptop GPU

### Describe the bug

That's old problem which had been reported in https://forums.developer.nvidia.com/t/sys-class-drm-enabled-reports-disabled-for-enabled-monitors/51187 , but it doesn't been solved until now.

I found that kernel updates `/sys/class/drm/*/enabled` by(https://github.com/torvalds/linux/blob/master/drivers/gpu/drm/drm_sysfs.c#L251):
```
	struct drm_connector *connector = to_drm_connector(device);
	bool enabled;

	enabled = READ_ONCE(connector->encoder);

	return sysfs_emit(buf, enabled ? "enabled\n" : "disabled\n");
```
Seems just check the existence of  field `connector->encoder` . I skimmed nvidia-drm sources, seems there is no assignment for `connector->encoder`, and it only uses `connector->nv_detected_encoder` .

Some softwares which depend on /sys/class/drm/*/enabled to detect monitor's status cannot work incorrectly when use nvidia card, for example, logind in laptop with nvidia card.

### To Reproduce

`cat /sys/class/drm/*/enabled`

### Bug Incidence

Once

### nvidia-bug-report.log.gz

[nvidia-bug-report.log.gz](https://github.com/user-attachments/files/20884280/nvidia-bug-report.log.gz)

**Comment by Binary-Eater** [comment]
Thanks @RMTT. I was doing my own experiments recently and found the same behavior as well. Looking into resolving this.

**Comment by Binary-Eater** [comment]
As a FYI, it's a bug if a DRM driver explicitly sets `connector->encoder`.

```
/**
 * drm_connector_attach_encoder - attach a connector to an encoder
 * @connector: connector to attach
 * @encoder: encoder to attach @connector to
 *
 * This function links up a connector to an encoder. Note that the routing
 * restrictions between encoders and crtcs are exposed to userspace through the
 * possible_clones and possible_crtcs bitmasks.
 *
 * Returns:
 * Zero on success, negative errno on failure.
 */
int drm_connector_attach_encoder(struct drm_connector *connector,
				 struct drm_encoder *encoder)
{
	/*
	 * In the past, drivers have attempted to model the static association
	 * of connector to encoder in simple connector/encoder devices using a
	 * direct assignment of connector->encoder = encoder. This connection
	 * is a logical one and the responsibility of the core, so drivers are
	 * expected not to mess with this.
	 *
	 * Note that the error return should've been enough here, but a large
	 * majority of drivers ignores the return value, so add in a big WARN
	 * to get people's attention.
	 */
	if (WARN_ON(connector->encoder))
		return -EINVAL;

	connector->possible_encoders |= drm_encoder_mask(encoder);

	return 0;
}
EXPORT_SYMBOL(drm_connector_attach_encoder);
```

**Comment by RMTT** [comment]
> Looking into resolving this

Thanks! This bug is very crucial for improving linux desktop experience with NVIDIA in laptops.

**Comment by Binary-Eater** [comment]
Wanted to update we have a fix for this issue internally.

**Comment by RMTT** [comment]
> Wanted to update we have a fix for this issue internally.

Thanks for your work! Will this fix be included in next release?

**Comment by abchauhan-nv** [comment]
Hi all, the issue was tracked on NVBug #5420364. This is now resolved and the fix will be available in a future driver release. Thanks

**Comment by ShadiestGoat** [comment]
Hi - is this fix supposed to be in current release? I seem to still be able to reproduce this on latest version

**Comment by Binary-Eater** [comment]
The fix I wrote has not landed in the current releases. I think @abchauhan-nv will update the thread when it's out.

**Comment by Binary-Eater** [comment]
We just had a new release

https://www.nvidia.com/en-us/drivers/details/253003/

**Comment by alexphanna** [comment]
This release did not fix this issue for me. `cat /sys/class/drm/*/enabled` still reports all disabled. I am using a 3060 and have tested both the 580.82.07 and 580.82.09 drivers, neither fix it for me. I am also on NixOS if that matters.

**Comment by RMTT** [comment]
> This release did not fix this issue for me. `cat /sys/class/drm/*/enabled` still reports all disabled. I am using a 3060 and have tested both the 580.82.07 and 580.82.09 drivers, neither fix it for me. I am also on NixOS if that matters.

I'm using 5070Ti Laptop with 580.82.09 driver. The problem had been fixed.

**Comment by alexphanna** [comment]
> > This release did not fix this issue for me. `cat /sys/class/drm/*/enabled` still reports all disabled. I am using a 3060 and have tested both the 580.82.07 and 580.82.09 drivers, neither fix it for me. I am also on NixOS if that matters.
> 
> I'm using 5070Ti Laptop with 580.82.09 driver. The problem had been fixed.

That's interesting, I am on a desktop and my monitor is plugged into an HDMI port on my graphics card. I feel like this shouldn't matter because the nouveau drivers show it as enabled. I am also on the latest kernel 6.16.7.

<img width="416" height="333" alt="Image" src="https://github.com/user-attachments/assets/fcbe3b98-5f11-483f-8e57-a027f7a858bc" />

**Comment by abchauhan-nv** [comment]
@alexphanna , Can you please capture a NVIDIA bug report from your system and attach it here? Thanks

**Comment by alexphanna** [comment]
Yes, here it is:

[nvidia-bug-report.log.gz](https://github.com/user-attachments/files/22498536/nvidia-bug-report.log.gz)

**Comment by Binary-Eater** [comment]
@alexphanna do you mind sharing the output of this command with the HDMI monitor plugged in using the 580.82.09 driver? I am a bit surprised since this is working for me with external GPUs as well. I am wondering if you have multiple DRM devices on your system, which is causing this confusion. Anyways, this command should give me a lot more insight.

```
realpath /sys/class/drm/*/{enabled,status} | xargs -I{} sh -c 'echo {}; cat {}'
```

Example output (with HDMI connected and the driver with the fix, illustrating the fix in action with HDMI on a 3080Ti).

```
[binary-eater@BINARY-EATER-TEST ~]$ realpath /sys/class/drm/*/{enabled,status} | xargs -I{} sh -c 'echo {}; cat {}'
/sys/devices/pci0000:00/0000:00:01.0/0000:01:00.0/drm/card0/card0-DP-1/enabled
disabled
/sys/devices/pci0000:00/0000:00:01.0/0000:01:00.0/drm/card0/card0-DP-2/enabled
disabled
/sys/devices/pci0000:00/0000:00:01.0/0000:01:00.0/drm/card0/card0-DP-3/enabled
disabled
/sys/devices/pci0000:00/0000:00:01.0/0000:01:00.0/drm/card0/card0-HDMI-A-1/enabled
enabled
/sys/devices/pci0000:00/0000:00:01.0/0000:01:00.0/drm/card0/card0-DP-1/status
disconnected
/sys/devices/pci0000:00/0000:00:01.0/0000:01:00.0/drm/card0/card0-DP-2/status
disconnected
/sys/devices/pci0000:00/0000:00:01.0/0000:01:00.0/drm/card0/card0-DP-3/status
disconnected
/sys/devices/pci0000:00/0000:00:01.0/0000:01:00.0/drm/card0/card0-HDMI-A-1/status
connected
```

**Comment by alexphanna** [comment]
Yea, here is the output:

```
/sys/devices/pci0000:00/0000:00:03.1/0000:2b:00.0/drm/card1/card1-DP-1/enabled
disabled
/sys/devices/pci0000:00/0000:00:03.1/0000:2b:00.0/drm/card1/card1-DP-2/enabled
disabled
/sys/devices/pci0000:00/0000:00:03.1/0000:2b:00.0/drm/card1/card1-DP-3/enabled
disabled
/sys/devices/pci0000:00/0000:00:03.1/0000:2b:00.0/drm/card1/card1-HDMI-A-1/enabled
disabled
/sys/devices/pci0000:00/0000:00:03.1/0000:2b:00.0/drm/card1/card1-DP-1/status
disconnected
/sys/devices/pci0000:00/0000:00:03.1/0000:2b:00.0/drm/card1/card1-DP-2/status
disconnected
/sys/devices/pci0000:00/0000:00:03.1/0000:2b:00.0/drm/card1/card1-DP-3/status
disconnected
/sys/devices/pci0000:00/0000:00:03.1/0000:2b:00.0/drm/card1/card1-HDMI-A-1/status
connected
```

I am not sure why my gpu says card 1, instead of 0. I only have one gpu and no integrated graphics. That may be the issue.

**Comment by ShadiestGoat** [comment]
FYI: I have the same issue on a laptop with integrated graphics. My connection is through dp (via usb-c)

**Comment by Binary-Eater** [comment]
Thanks a lot! That's definitely coming from the NVIDIA device from comparing that output with the bug report you provided.
My prediction has to do with something strange causing a discrepancy in your particular setup that is not traditionally seen, hence the discrepancy.

For some background, here is the change we added to fix the issue seen originally, https://github.com/NVIDIA/open-gpu-kernel-modules/blob/87c0b1247370e42bd22bb487a683ec513a177b3b/kernel-open/nvidia-drm/nvidia-drm-modeset.c#L705-L711

The goal was that this should be identical in logic to what `nouveau` and `amdgpu` do in logic.

In comparison, `/sys/class/drm/*/status` is updated through the following path.

* https://github.com/NVIDIA/open-gpu-kernel-modules/blob/87c0b1247370e42bd22bb487a683ec513a177b3b/kernel-open/nvidia-drm/nvidia-drm-connector.c#L234
* https://github.com/NVIDIA/open-gpu-kernel-modules/blob/87c0b1247370e42bd22bb487a683ec513a177b3b/kernel-open/nvidia-drm/nvidia-drm-connector.c#L153

Let me try to reproduce this using a laptop device. If I cannot create an internal reproduction, I might need to provide debug patches for those still experiencing the same issue to help debug this further.

**Comment by alexphanna** [comment]
Thanks, I fixed the `card1` thing by adding this kernel parameter: `initcall_blacklist=simpledrm_platform_driver_init`, but that didn't solve the problem. The output is the same as before, but with `card0` instead of `card1`.

**Comment by Binary-Eater** [comment]
Yeah, I suspect card1 vs card0 was just an artifact of `simpledrm` and not an issue when you shared the output. Running some experiments to try to reproduce this issue.

**Comment by ShadiestGoat** [comment]
> discrepancy in your particular setup that is not traditionally seen

What types of things could they be? I'd love to provide more details. I'm on arch W/ xorg

**Comment by Binary-Eater** [comment]
One example would be the X clients used. GNOME vs i3 etc. Each client handles RandR hotplug events differently.

**Comment by Binary-Eater** [comment]
I managed to create a reproduction of the issue. The problem is that our X driver bypasses nvidia-drm, so the newly added call to nvidia-drm does not get hit. Instead with our X driver, we directly make use of the nvidia-modeset driver ioctls. With Wayland, the compositor makes use of nvidia-drm, so the state is updated correctly. This requires some thought process because we do not want to make the needed DRM call from nvidia-modeset directly.

```
[binary-eater@BINARY-EATER-TEST ~]$ realpath /sys/class/drm/*/{enabled,status} | xargs -I{} sh -c 'echo {}; cat {}'
/sys/devices/pci0000:00/0000:00:01.0/0000:01:00.0/drm/card0/card0-DP-1/enabled
disabled
/sys/devices/pci0000:00/0000:00:01.0/0000:01:00.0/drm/card0/card0-DP-2/enabled
disabled
/sys/devices/pci0000:00/0000:00:01.0/0000:01:00.0/drm/card0/card0-DP-3/enabled
disabled
/sys/devices/pci0000:00/0000:00:01.0/0000:01:00.0/drm/card0/card0-HDMI-A-1/enabled
disabled
/sys/devices/pci0000:00/0000:00:01.0/0000:01:00.0/drm/card0/card0-DP-1/status
disconnected
/sys/devices/pci0000:00/0000:00:01.0/0000:01:00.0/drm/card0/card0-DP-2/status
disconnected
/sys/devices/pci0000:00/0000:00:01.0/0000:01:00.0/drm/card0/card0-DP-3/status
disconnected
/sys/devices/pci0000:00/0000:00:01.0/0000:01:00.0/drm/card0/card0-HDMI-A-1/status
connected
```

**Comment by alexphanna** [comment]
Ah I see, that would make sense because I am also on X11 and use dwm.

**Comment by Binary-Eater** [comment]
The advantage of the "new" status sysfs node is it enables a driver to update the state of the display connection without needing to go through the DRM atomic modesetting API. Ideally, logind would make use of this API instead for the purpose of detecting docking.

**Comment by alexphanna** [comment]
That makes sense. Is there another way to access equivalent information to `/sys/class/drm/*/enabled` then?

**Comment by Binary-Eater** [comment]
`/sys/class/drm/*/status` would be the atomic modeset equivalent to the legacy modeset sysfs node `/sys/class/drm/*/enabled`. The nice thing with `status` is that it can be updated from our base non-DRM modesetting driver, `nvidia-modeset`.

**Comment by alexphanna** [comment]
Oh okay, I may be completely mistaken then. I was trying to get `/sys/class/drm/*/enabled` to work because I needed a way to check if my monitor was on or off programmatically. I was under the impression that `enabled` and `status` would be different if for example the monitor was off, but the gpu was still connected. If the `enabled` value is equivalent to the `status` value then it is not really important for me.

**Comment by Binary-Eater** [comment]
@alexphanna for what you want to achieve, you will need to use both the `status` and `dpms` sysfs nodes.

**Comment by ShadiestGoat** [comment]
Hm that doesn't 100% work for me. I need it to work since systemctl uses it for "docked mode" detection, allowing me to like close a laptop without it sleeping. Is there another workaround?

**Comment by Binary-Eater** [comment]
I think the correct thing for logind to do is account for both sysfs nodes. It is expected for atomic modesetting drivers to not implement the legacy helper that populates the information for the legacy sysfs node. That sysfs node is supported by drivers just to not break uapi from the time those drivers supported the legacy modeset path. The difference for X is with the sunsetting of X development, DRM driver developers implemented a X modesetting driver that can use DRM kernel drivers to drive the X display. However, this removes the opportunity for enhancing performance/improving behavior for GLX support. We want to have an enhanced GLX experience, so we still ship a custom X userspace driver and do not plumb through DRM with this driver.

**Comment by Binary-Eater** [comment]
If you wanted, you could use the X modesetting userspace driver which would make use of `nvidia-drm` in place of the NVIDIA X userspace driver, but you would be choosing to throw away GLX performance.

**Comment by ShadiestGoat** [comment]
I see, sad. I guess this is a sign to move to Wayland anyways
